name: next.js CI and Deploy

on:
  push:
    branches:
      - Develop

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Check if Docker Image Exists
      id: check-image
      run: |
        if sudo docker inspect mbccoins-app > /dev/null 2>&1; then
          echo "::set-output name=image_exists::true"
        else
          echo "::set-output name=image_exists::false"
        fi

    - name: Check if Docker Container Exists
      id: check-container
      run: |
        if sudo docker inspect mbccoins-app-1 > /dev/null 2>&1; then
          echo "::set-output name=container_exists::true"
        else
          echo "::set-output name=container_exists::false"
        fi

    - name: Stop and Remove Previous Docker Container (if exists)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 20.78.39.206
        username: MBCcoin
        password: tradingCoin123
        port: 22
        script: |
          if [ "$CONTAINER_EXISTS" == "true" ]; then
            sudo docker stop mbccoins-app-1 || true
            sudo docker rm mbccoins-app-1 || true
          fi
          if [ "$IMAGE_EXISTS" == "true" ]; then
            sudo docker rmi mbccoins-app || true
          fi

    - name: Clone Repository and Build
      run: |
        cd ~/MBCCoins
        sudo git pull origin Develop
        sudo docker compose up --build -d
