name: next.js CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Stop and Remove Previous Docker Container
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: 20.48.90.191
        username: MBCcoin
        password: tradingCoin123
        port: 22
        script: |
          sudo docker stop docker-tes-app-1 || true 
          sudo docker rm docker-tes-app-1 || true 
          sudo docker rmi docker-tes-app || true 
          cd /home/MBCcoin/docker-tes && git pull origin main && sudo docker compose up --build -d
