name: Node.js CI and Deploy

on:
  push:
    branches:
      - Develop

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Stop and Remove Previous Docker Container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 20.78.39.206
        username: MBCcoin
        password: tradingCoin123
        script: |
          sudo docker stop MBCCoins-app-1 || true 
          sudo docker rm MBCCoins-app-1 || true 
          sudo docker rmi MBCCoins-app || true 
          cd /home/MBCcoin/MBCCoins
          git pull origin Develop && sudo docker compose up --build -d
  
