name: Node.js CI and Deploy

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'


    - name: Stop and Remove Previous Docker Container
      uses: appleboy/ssh-action@v1.0.0
      with:
        key : ${{secrets.SSH_SECRET}}
        username: pabanasuryp
        host: ${{secrets.HOST_SECRETS}}
        script: sudo mkdir new-test
          

