name: Node.js CI and Deploy

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Build
      run: | 
        npm install
        npm run build

    - name: Stop and Remove Previous Docker Container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST_SECRETS}}
        username: ${{secrets.USERNAME_SECRETS}}
        password: ${{secrets.PASSWORD_SECRETS}}
        script: |
          sudo docker stop mbccoins-app-1 || true 
          sudo docker rm mbccoins-app-1 || true 
          sudo docker rmi mbccoins-app || true 
          cd /home/MBCcoin/newWeb/MBCCoins
          sudo git pull origin Master && sudo docker compose up --build -d

